name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            python3-dev \
            zlib1g-dev \
            libncurses5-dev \
            libglib2.0-dev \
            libsdl2-dev \
            libffi-dev

      - name: Install Kivy and build dependencies
        run: |
          pip install kivy==2.3.0 kivy_examples --no-binary kivy
          pip install Cython==3.0.8  # You may need to specify the version

      - name: Build APK
        run: |
          python -m buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-debug
          path: ${{ steps.buildozer.outputs.filename }}
